### ISSUE TITLE
How to make autotext ?

### ISSUE THREAD

**Issue by azzamsa** [OpenTaal/LanguagePack#4]
Hi.
I am in progress to build Indonesian Language Pack.
Your repository style is very good to follow.

How do you guys create the word list of [auto text](https://github.com/OpenTaal/LanguagePack/blob/Dutch/src/main/res/xml/nl_autotext.xml) , do you write this thousand words manually or take valid word from dictionary and scramble the wrong word with script ?

Thanks.

**Comment by PanderMusubi** [comment]
We have a database with common mistakes and their corrections. That has been build over the years with various contributions. Perhaps you can find some sources for your language and ask if you are allowed to used them. Good luck.

**Comment by azzamsa** [comment]
So it's mean build manually by people ?

**Comment by PanderMusubi** [comment]
Our database, yes.

**Comment by azzamsa** [comment]
Thank you :)
